version: "3.4"

services:
  memo:
    build:
      context: ./
    command: [ "clojure", "-M", "-m", "memo.service" ]
    ports:
      - "8080:8080"
    environment:
      - CLOUDAMQP_URL=amqp://guest:guest@rabbitmq
    depends_on:
      - rabbitmq
    logging:
      driver: "local"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8000:15672"
    logging:
      driver: "local"

